name: cripto_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  integration_test:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^5.0.4
  dio: ^5.1.1
  path_provider: ^2.0.15
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  intl: ^0.17.0
  retrofit: ^4.0.1
  hive: ^2.2.3
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  bloc_test: ^9.0.3
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  lint: ^2.0.1
  retrofit_generator: ^6.0.0+1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - env/