// Mocks generated by Mockito 5.4.4 from annotations
// in cripto_app/test/home_test/unit_test/mock_home_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cripto_app/home/domain/respositories/home_repository.dart'
    as _i3;
import 'package:cripto_app/resources/base_state.dart' as _i2;
import 'package:cripto_app/resources/models/coin_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiRepository extends _i1.Mock implements _i3.HomeApiRepository {
  MockHomeApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.CoinModel>>> getCoins() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoins,
          [],
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.CoinModel>>>.value(
            _FakeDataState_0<List<_i5.CoinModel>>(
          this,
          Invocation.method(
            #getCoins,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.CoinModel>>>);

  @override
  _i4.Future<bool> saveFavorite(
    String? uid,
    _i5.CoinModel? coin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavorite,
          [
            uid,
            coin,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
